version: "3"
services: 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
    ports: 
      - 5433:5432
    volumes:
      - ./resources/database:/docker-entrypoint-initdb.d
  app:
    build: .
    depends_on: 
      - db
    ports: 
      - 3000:3000

    
    